### ISSUE TITLE
"ValueError: No JSON object could be decoded error"

### ISSUE THREAD

**Issue by rodpacker** [Kenshii/500px-Bot#28]
Hey mate,

thx for sharing this script.  I am getting the following error after having installed python dependencies and having changed username and pw:

python /home/.../Desktop/500px-Bot-master/500px.py 
Traceback (most recent call last):                                                                       
  File "/home/.../Desktop/500px-Bot-master/500px.py", line 230, in <module>                              
    retrieveLists()                                                                                      
  File "/home/.../Desktop/500px-Bot-master/500px.py", line 56, in retrieveLists                          
    pendingFollowList = json.loads(f.read())                                                             
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                         
    return _default_decoder.decode(s)                                                                    
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                         
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                    
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

any idea what could be causing this?

thanks for your help

**Comment by rodpacker** [comment]
Is my question too generic or is this not getting any support anymore?

thx

**Comment by rodpacker** [comment]
Hi,

is my question too simple or is this not getting supported anymore?

thanks

**Comment by shane-tw** [comment]
Sorry, this isn't really being supported anymore as I've lost interest in it and I'm working full time now so I don't have time to work on it anyway.  
Your question wasn't too simple, it hasn't come up before.

**Comment by rodpacker** [comment]
Hey mate, sorry only read this now.  bummer, but thx for taking the time to reply anyway.

cheers

Ron

 
 

Gesendet: Montag, 19. Februar 2018 um 01:27 Uhr
Von: "Shane O Donovan" <notifications@github.com>
An: shanepm/500px-Bot <500px-Bot@noreply.github.com>
Cc: rodpacker <ronthedon@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [shanepm/500px-Bot] "ValueError: No JSON object could be decoded error" (#28)


Sorry, this isn't really being supported anymore as I've lost interest in it and I'm working full time now so I don't have time to work on it anyway.
Your question wasn't too simple, it hasn't come up before.

**Comment by dalerazimov** [comment]
Hi.

This happens when you reach a certain size of data (here - number of followers or following), it cannot write data and crashes.
